name       : screenkey
version    : '1.0'
release    : 5
source     :
    - https://gitlab.com/screenkey/screenkey/-/archive/v1.0/screenkey-v1.0.tar.gz : e4d841ed599c73b71b99f7e06482995addc2e626215be0a12d4e3ca66cdee3c2
homepage   : https://www.thregr.org/~wavexx/software/screenkey/
license    : GPL-3.0-or-later
component  : desktop
summary    : A screencast tool to display your keys.
description: |
    A screencast tool to display your keys, inspired by Screenflick.
builddeps  :
    - libgtk-3
    - libxtst
    - python-distutils-extra
    - python3-cairo
    - python3-gobject
rundeps    :
    - font-awesome-ttf
    - python3-cairo
    - python3-gobject
build      : |
    %python3_setup
install    : |
    %python3_install
    rm -rf $installdir/usr/share/doc
check      : |
    %python3_test
