name       : screenkey
version    : '1.4'
release    : 10
source     :
    - https://www.thregr.org/~wavexx/software/screenkey/releases/screenkey-1.4.tar.gz : d7347e31fab4a5b18da431e3fc26f39700e99a505eb0c0168295adc12c8dd4f7
homepage   : https://www.thregr.org/~wavexx/software/screenkey/
license    : GPL-3.0-or-later
component  : desktop
summary    : A screencast tool to display your keys
description: |
    Screenkey is a useful tool for presentations or screencasts. It is inspired by ScreenFlick and initially based on the key-mon project code.
builddeps  :
    - python-babel
rundeps    :
    - font-awesome-ttf
    - python-gobject
    - python3-cairo
    - slop
build      : |
    %python3_setup
install    : |
    %python3_install
    rm -rf $installdir/usr/share/doc
