name       : screenkey
version    : '1.2'
release    : 7
source     :
    - https://gitlab.com/screenkey/screenkey/-/archive/v1.2/screenkey-v1.2.tar.gz : cac76751981857cb65ae3e892285ca8f01e7905e1279327cf2bcf1fec0f0fb69
homepage   : https://www.thregr.org/~wavexx/software/screenkey/
license    : GPL-3.0-or-later
component  : desktop
summary    : A screencast tool to display your keys.
description: |
    A screencast tool to display your keys, inspired by Screenflick.
builddeps  :
    - libgtk-3
    - libxtst
    - python-distutils-extra
    - python-gobject
    - python3-cairo
rundeps    :
    - font-awesome-ttf
    - python-gobject
    - python3-cairo
    - slop
build      : |
    %python3_setup
install    : |
    %python3_install
    rm -rf $installdir/usr/share/doc
check      : |
    %python3_test
