name       : screenkey
version    : '1.3'
release    : 8
source     :
    - https://www.thregr.org/~wavexx/software/screenkey/releases/screenkey-1.3.tar.gz : 82e3ff4069744a2e92109788b76cec1195a4491b456ced175c1b79ed96037c03
homepage   : https://www.thregr.org/~wavexx/software/screenkey/
license    : GPL-3.0-or-later
component  : desktop
summary    : A screencast tool to display your keys
description: |
    Screenkey is a useful tool for presentations or screencasts. It is inspired by ScreenFlick and initially based on the key-mon project code.
builddeps  :
    - python-distutils-extra
rundeps    :
    - font-awesome-ttf
    - python-gobject
    - python3-cairo
    - slop
build      : |
    %python3_setup
install    : |
    %python3_install
    rm -rf $installdir/usr/share/doc
