name       : screenkey
version    : '0.9'
release    : 4
source     :
    - https://gitlab.com/screenkey/screenkey/-/archive/screenkey-0.9/screenkey-screenkey-0.9.tar.gz : 20f0b5415906cfb5cf41ca4f61c4ca22d4a13413aed87980d4d1a03dc92e7157
homepage   : https://www.thregr.org/~wavexx/software/screenkey/
license    : GPL-3.0-or-later
component  : desktop
summary    : A screencast tool to display your keys.
description: |
    A screencast tool to display your keys, inspired by Screenflick.
builddeps  :
    - pkgconfig(pygtk-2.0)
    - python-distutils-extra
    - python-setuptools
    - python-setuptools-git
rundeps    :
    - font-awesome-ttf
    - python-gtk2
    - slop
build      : |
    %python_setup
install    : |
    %python_install
    rm -rf $installdir/usr/share/doc
check      : |
    %python_test
